more

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -21,36 +21,40 @@ jobs:
       # Install local action
       - name: Check out repository
         uses: actions/checkout@v2
-
-      - name: Install local action packages
-        uses: ./ # this action
-        with:
-          node-version: '16.0.0'
-          skip-checkout: true
-          skip-setup-node: false
-          skip-npm-install: true
-      - name: Get env node version
-        id: node-version-env
-        run: echo "::set-output name=value::$(node --version)"
-      - name: Check node version env
-        if: ${{ steps.node-version-before.outputs.value != '16.0.0' }}
-        uses: actions/github-script@v3
-        with:
-          script: core.setFailed('Node version should match set version')
-
       - name: Install local action packages
         uses: ./ # this action
         with:
           path: 'put_repo_here'
-          skip-checkout: false
-          skip-setup-node: true
-          skip-npm-install: true
-      - name: Check repo directory
-        run: |
-          directory="${{ github.workspace }}/put_repo_here"
 
-          # bash check if directory exists
-          if [ ! -d $directory ]; then
-            echo "Failed to install repo at path"
-            exit 1
-          fi
+      # - name: Install local action packages
+      #   uses: ./ # this action
+      #   with:
+      #     node-version: '16.0.0'
+      #     skip-checkout: true
+      #     skip-setup-node: false
+      #     skip-npm-install: true
+      # - name: Get env node version
+      #   id: node-version-env
+      #   run: echo "::set-output name=value::$(node --version)"
+      # - name: Check node version env
+      #   if: ${{ steps.node-version-before.outputs.value != '16.0.0' }}
+      #   uses: actions/github-script@v3
+      #   with:
+      #     script: core.setFailed('Node version should match set version')
+
+      # - name: Install local action packages
+      #   uses: ./ # this action
+      #   with:
+      #     path: 'put_repo_here'
+      #     skip-checkout: false
+      #     skip-setup-node: true
+      #     skip-npm-install: true
+      # - name: Check repo directory
+      #   run: |
+      #     directory="${{ github.workspace }}/put_repo_here"
+
+      #     # bash check if directory exists
+      #     if [ ! -d $directory ]; then
+      #       echo "Failed to install repo at path"
+      #       exit 1
+      #     fi
